/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /Eft3zc2fcmU0jvRgVNb1/jlzk2I2OpTkwIHOPUw9ljbxjdAGuqiMgKXpCnSU71gxifHgFzyv0t+JQCi7dKZ5Q==
 */

/* eslint-disable */
// tslint:disable

interface Actor {
  actor_id: number & {readonly __brand?: 'actor_actor_id'}
  first_name: string
  last_name: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
}
export default Actor;

interface Actor_InsertParameters {
  actor_id: number & {readonly __brand?: 'actor_actor_id'}
  first_name: string
  last_name: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
}
export type {Actor_InsertParameters}
