/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: QKdalO5rerZhFsia3fpIMwLbzWPPGmzIwveOrmYLgSwk9wcE+190iCmvTmk0o5UHXy7264q9WnCeL9weRltmsQ==
 */

/* eslint-disable */
// tslint:disable

import City from './city'

interface Address {
  address: string
  address2: (string) | null
  address_id: number & {readonly __brand?: 'address_address_id'}
  city_id: City['city_id']
  district: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
  location: unknown
  phone: string
  postal_code: (string) | null
}
export default Address;

interface Address_InsertParameters {
  address: string
  address2?: (string) | null
  address_id: number & {readonly __brand?: 'address_address_id'}
  city_id: City['city_id']
  district: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
  location: unknown
  phone: string
  postal_code?: (string) | null
}
export type {Address_InsertParameters}
