/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hXjKioQH0qO1S6t0reGxF+dkTR6LndZ2MDl3h2bLn9mEp18OjJHuITK95lWciuJ6WK972OVljT/T+qwWRhIzAg==
 */

/* eslint-disable */
// tslint:disable

interface Category {
  category_id: (boolean | number) & {readonly __brand?: 'category_category_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
  name: string
}
export default Category;

interface Category_InsertParameters {
  category_id: (boolean | number) & {readonly __brand?: 'category_category_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
  name: string
}
export type {Category_InsertParameters}
