/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aUmRttAtmTCkCMxRg7yi8v2QDmfVFGWLSxy3sYg33AICJ9Eyq7Pko7PVN1uBqSOD0iJdWFHLaM9vH+jAr1kAWg==
 */

/* eslint-disable */
// tslint:disable

interface Committees {
  committee_id: number & {readonly __brand?: 'committees_committee_id'}
  name: (string) | null
}
export default Committees;

interface Committees_InsertParameters {
  committee_id: number & {readonly __brand?: 'committees_committee_id'}
  name?: (string) | null
}
export type {Committees_InsertParameters}
