/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PsVofi7saQVs/LT5+4D7D+hvVwcSPaSsS7Zo4gJ0vWC4Rq23dLKd+dvDJMj3tssk0HkAHSwGSGUOmwWn8dPWNA==
 */

/* eslint-disable */
// tslint:disable

interface Competition {
  Challenge_id: (number) | null
  score: (number) | null
  student_id: (number) | null
  student_name: (string) | null
}
export default Competition;

interface Competition_InsertParameters {
  Challenge_id?: (number) | null
  score?: (number) | null
  student_id?: (number) | null
  student_name?: (string) | null
}
export type {Competition_InsertParameters}
