/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: a8VpfqNN0w4JtMx6Lf9XlAeiqBqPQNhAthEF5b7mY2j4XkjpwQJBpE7bywZ8cleLITcc6bHSbVW9N0N5PkzIgA==
 */

/* eslint-disable */
// tslint:disable

import Country from './country'

interface Countrylanguage {
  CountryCode: Country['Code']
  /**
   * @default F
   */
  IsOfficial: ("T" | "F")
  Language: string & {readonly __brand?: 'countrylanguage_Language'}
  /**
   * @default 0.0
   */
  Percentage: number
}
export default Countrylanguage;

interface Countrylanguage_InsertParameters {
  CountryCode?: Country['Code']
  /**
   * @default F
   */
  IsOfficial?: ("T" | "F")
  Language?: string & {readonly __brand?: 'countrylanguage_Language'}
  /**
   * @default 0.0
   */
  Percentage?: number
}
export type {Countrylanguage_InsertParameters}
