/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9z4ZUEvE92YhQjk1FJKR4TWl5p3ki1QeefMpS2l+daDo0PctnOTGRVZa6pVZ4EHmMZfy7fGWvO/SOsBJ2PXg5g==
 */

/* eslint-disable */
// tslint:disable

interface Country {
  country: string
  country_id: number & {readonly __brand?: 'country_country_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
}
export default Country;

interface Country_InsertParameters {
  country: string
  country_id: number & {readonly __brand?: 'country_country_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
}
export type {Country_InsertParameters}
