/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8rYiTdQiaaxeYgrW2974JXRsx3FBX4V3ZfekwK75NwsCh8ASudPim2rlVZGsKrPgc6HdyADmkgPUzYDgbNJKwg==
 */

/* eslint-disable */
// tslint:disable

import Address from './address'
import Store from './store'

interface Customer {
  /**
   * @default 1
   */
  active: (boolean | number)
  address_id: Address['address_id']
  create_date: (string | Date)
  customer_id: number & {readonly __brand?: 'customer_customer_id'}
  email: (string) | null
  first_name: string
  last_name: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: ((string | Date)) | null
  store_id: Store['store_id']
}
export default Customer;

interface Customer_InsertParameters {
  /**
   * @default 1
   */
  active?: (boolean | number)
  address_id: Address['address_id']
  create_date: (string | Date)
  customer_id: number & {readonly __brand?: 'customer_customer_id'}
  email?: (string) | null
  first_name: string
  last_name: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: ((string | Date)) | null
  store_id: Store['store_id']
}
export type {Customer_InsertParameters}
