/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vtErXSKmGS9uy9nvO31Xm7zOmWt1V25d5nD7zyo+nTcDyifwnuBnxvclsG3k/pu+iZeNZhjhwRg+Jx4/pQ5sCA==
 */

/* eslint-disable */
// tslint:disable

interface Employee {
  age: (number) | null
  firstname: (string) | null
  lastname: (string) | null
  location: (string) | null
  salary: (number) | null
}
export default Employee;

interface Employee_InsertParameters {
  age?: (number) | null
  firstname?: (string) | null
  lastname?: (string) | null
  location?: (string) | null
  salary?: (number) | null
}
export type {Employee_InsertParameters}
