/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0ZsK1WeAeVJLpNLk30CfJjxRco2bYliqgzwU5Cgdeqe4pMcO/4p2XMjxvJW/yOjaztOtTIpC8fFpobIaK13LDQ==
 */

/* eslint-disable */
// tslint:disable

interface Faithful {
  erLength: (number) | null
  erwait: (number) | null
  index: (number) | null
}
export default Faithful;

interface Faithful_InsertParameters {
  erLength?: (number) | null
  erwait?: (number) | null
  index?: (number) | null
}
export type {Faithful_InsertParameters}
