/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gKjBY3N5VmjNRx0kHAz7FUkF1yV3tikTeZ8APLyAut+F5dg4+tYj2jDhhZ7pT6RV3kZKd2gcnuK3BiWMRmVU4w==
 */

/* eslint-disable */
// tslint:disable

interface FilmText {
  description: (string) | null
  film_id: number & {readonly __brand?: 'film_text_film_id'}
  title: string
}
export default FilmText;

interface FilmText_InsertParameters {
  description?: (string) | null
  film_id: number & {readonly __brand?: 'film_text_film_id'}
  title: string
}
export type {FilmText_InsertParameters}
