/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 31fAp+SMc4kT99cxU+Sxtpk5PNpJ6Mh+VIdBXNFfYifLUI2Cshm85NkSiwc6edF7l2dkKIndC7MY1oA6XFuMRA==
 */

/* eslint-disable */
// tslint:disable

import Actor from './actor'
import Film from './film'

interface FilmActor {
  actor_id: Actor['actor_id']
  film_id: Film['film_id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
}
export default FilmActor;

interface FilmActor_InsertParameters {
  actor_id: Actor['actor_id']
  film_id: Film['film_id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
}
export type {FilmActor_InsertParameters}
