/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8kP/RvTWWDYv2HbUCo4XYsVKenZlf0epFiBGCvsBeF1PGmT9Na/tXm7Kv0IAXLbtLYKmdG9pgN4ExClobVCB5A==
 */

/* eslint-disable */
// tslint:disable

import Category from './category'
import Film from './film'

interface FilmCategory {
  category_id: Category['category_id']
  film_id: Film['film_id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
}
export default FilmCategory;

interface FilmCategory_InsertParameters {
  category_id: Category['category_id']
  film_id: Film['film_id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
}
export type {FilmCategory_InsertParameters}
