/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: glyNTK3Fa5q5piNcxUiI0hNDZylSUhXYcTTiRjQ8QiGDzPS1UWGcRvAFVp8px2xjPve97y28ztGH8dOWe5QXOg==
 */

/* eslint-disable */
// tslint:disable

import Film from './film'
import Store from './store'

interface Inventory {
  film_id: Film['film_id']
  inventory_id: number & {readonly __brand?: 'inventory_inventory_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
  store_id: Store['store_id']
}
export default Inventory;

interface Inventory_InsertParameters {
  film_id: Film['film_id']
  inventory_id: number & {readonly __brand?: 'inventory_inventory_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
  store_id: Store['store_id']
}
export type {Inventory_InsertParameters}
