/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yXnitNUy4MQHHw6vt0+gCNGL1nWTjHFRnjuQyJwDFhcjaprFRmbhBBdvN6RWdGPSJ707TigAt7QCuRoyfmJKYQ==
 */

/* eslint-disable */
// tslint:disable

interface Language {
  language_id: (boolean | number) & {readonly __brand?: 'language_language_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
  name: string
}
export default Language;

interface Language_InsertParameters {
  language_id: (boolean | number) & {readonly __brand?: 'language_language_id'}
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
  name: string
}
export type {Language_InsertParameters}
