/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: px3hRM52kwJBF9RZCQKC7uYLnvaMEVV3r0UPFJGg8vzmMgtWAEnwSdpI27N5UgMS2scZiXGlEKqLcMPDltFIJQ==
 */

/* eslint-disable */
// tslint:disable

interface Manjo {
  age: (number) | null
  location: (string) | null
  name: (string) | null
  salary: (number) | null
}
export default Manjo;

interface Manjo_InsertParameters {
  age?: (number) | null
  location?: (string) | null
  name?: (string) | null
  salary?: (number) | null
}
export type {Manjo_InsertParameters}
