/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: bMpUSztIgmcGHn8tdBaZRGFfbx6doXGwbM20s+UCgwLgZNid0lNJlk/I1lGdTIBNxddgsDaeDpak9XvE+hGvGA==
 */

/* eslint-disable */
// tslint:disable

import Customer from './customer'
import Rental from './rental'
import Staff from './staff'

interface Payment {
  amount: unknown
  customer_id: Customer['customer_id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: ((string | Date)) | null
  payment_date: (string | Date)
  payment_id: number & {readonly __brand?: 'payment_payment_id'}
  rental_id: (Rental['rental_id']) | null
  staff_id: Staff['staff_id']
}
export default Payment;

interface Payment_InsertParameters {
  amount: unknown
  customer_id: Customer['customer_id']
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: ((string | Date)) | null
  payment_date: (string | Date)
  payment_id: number & {readonly __brand?: 'payment_payment_id'}
  rental_id?: (Rental['rental_id']) | null
  staff_id: Staff['staff_id']
}
export type {Payment_InsertParameters}
