/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: qG0nmQ844+mu4p+ReSrm2sWblsggIWPrYlEqQH8sR0GcjuzLnkN8tbvWZpduQ0uY4ZWpoBbFTDmTE6jniq7Ytw==
 */

/* eslint-disable */
// tslint:disable

interface Processlist {
  COMMAND: (string) | null
  DB: (string) | null
  EXECUTION_ENGINE: (("PRIMARY" | "SECONDARY")) | null
  HOST: (string) | null
  ID: (string | number | BigInt) & {readonly __brand?: 'processlist_ID'}
  INFO: (unknown) | null
  STATE: (string) | null
  TIME: ((string | number | BigInt)) | null
  USER: (string) | null
}
export default Processlist;

interface Processlist_InsertParameters {
  COMMAND?: (string) | null
  DB?: (string) | null
  EXECUTION_ENGINE?: (("PRIMARY" | "SECONDARY")) | null
  HOST?: (string) | null
  ID: (string | number | BigInt) & {readonly __brand?: 'processlist_ID'}
  INFO?: (unknown) | null
  STATE?: (string) | null
  TIME?: ((string | number | BigInt)) | null
  USER?: (string) | null
}
export type {Processlist_InsertParameters}
