/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: l3fsCOwkve5dlU5/2gv/+WUUwH79fieALefCTHWWVutef/GMsIz+dnvlvxEYEwjFzV7K1rE+p9GVVbp7aXsXvA==
 */

/* eslint-disable */
// tslint:disable

interface Register {
  email: (string) | null
  firstname: (string) | null
  lastname: (string) | null
  password: (string) | null
}
export default Register;

interface Register_InsertParameters {
  email?: (string) | null
  firstname?: (string) | null
  lastname?: (string) | null
  password?: (string) | null
}
export type {Register_InsertParameters}
