/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ghE3YGBOeWbR3PWDmkcFHZfsOilXssBiXSc9HlsvIRX84A0Hvh7H/QA26uuKTxtt3DZ6Rx2h/HsBzvq+aQ00PA==
 */

/* eslint-disable */
// tslint:disable

import Address from './address'
import Store from './store'

interface Staff {
  /**
   * @default 1
   */
  active: (boolean | number)
  address_id: Address['address_id']
  email: (string) | null
  first_name: string
  last_name: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update: (string | Date)
  password: (string) | null
  picture: (unknown) | null
  staff_id: (boolean | number) & {readonly __brand?: 'staff_staff_id'}
  store_id: Store['store_id']
  username: string
}
export default Staff;

interface Staff_InsertParameters {
  /**
   * @default 1
   */
  active?: (boolean | number)
  address_id: Address['address_id']
  email?: (string) | null
  first_name: string
  last_name: string
  /**
   * @default CURRENT_TIMESTAMP
   */
  last_update?: (string | Date)
  password?: (string) | null
  picture?: (unknown) | null
  staff_id: (boolean | number) & {readonly __brand?: 'staff_staff_id'}
  store_id: Store['store_id']
  username: string
}
export type {Staff_InsertParameters}
