/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ACeBRuB4vQypb7Eueg/aQC7DjK+sZyucXdDBHnazVFYSpTi28Q9s+72Qk6i2P4MhO2urB3928UOz1/PHIDxAzw==
 */

/* eslint-disable */
// tslint:disable

interface Test {
  FirstName: (string) | null
  Identifier: (number) | null
  LastName: (string) | null
  Username: (string) | null
}
export default Test;

interface Test_InsertParameters {
  FirstName?: (string) | null
  Identifier?: (number) | null
  LastName?: (string) | null
  Username?: (string) | null
}
export type {Test_InsertParameters}
